<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serde" />
    <PackageReference Include="Serde.CmdLine" />
    <PackageReference Include="StaticCS">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <!-- Dependencies for Roslyn -->
    <Reference Include="$(_RoslynRestoreDirectory)microsoft.net.compilers.toolset/$(_RoslynVersion)/tasks/Microsoft.Build.Tasks.CodeAnalysis.dll" />
    <Content Include="$(_RoslynRestoreDirectory)microsoft.net.compilers.toolset/$(_RoslynVersion)/tasks/netcore/bincore/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <LinkBase>bincore</LinkBase>
    </Content>

    <PackageReference Include="Microsoft.Build.Utilities.Core" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" />

    <!-- NuGet restore dependencies -->
    <ProjectReference Include="../../external/nuget.client/src/NuGet.Core/NuGet.Commands/NuGet.Commands.csproj" />
    <ProjectReference Include="../../external/nuget.client/src/NuGet.Core/NuGet.Protocol/NuGet.Protocol.csproj" />
    <ProjectReference Include="../../external/nuget.client/src/NuGet.Core/NuGet.ProjectModel/NuGet.ProjectModel.csproj" />
    <ProjectReference Include="../../external/nuget.client/src/NuGet.Core/NuGet.Configuration/NuGet.Configuration.csproj" />

    <!-- Ref assemblies from refpack -->
    <Content Include="$(_RoslynRestoreDirectory)microsoft.netcore.app.ref/$(_MicrosoftNetcoreappRefVersion)/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <LinkBase>microsoft.netcore.app.ref</LinkBase>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MiniBuild\MiniBuild.csproj" />
  </ItemGroup>
</Project>
